#!/bin/sh -e

if [ "$1" = "configure" ]; then
    if [ -z "$2" ]; then
        # initial installation
        if [ ! -f /var/lib/pen/keys/libp2p.key ]; then
            /usr/bin/pen init --config /etc/pen/pen.yaml >/dev/null
            chown -R pen:pen /var/lib/pen
        fi
        echo "
Logs:   journalctl -f -u pen.service
Config: /etc/pen/pen.yaml

Pen requires an Ethereum endpoint to function. By default is using ws://localhost:8546 ethereum endpoint.
If needed obtain a free Infura account and set:
`swap-endpoint: wss://goerli.infura.io/ws/v3/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`
It is recommended to use external signer with pen.
Check documentation for more info:
- External signer

After you finish configuration run 'sudo pen-get-addr'.
        "
    fi

    # allow group members (pen user) to use clef's socket
    if [ -S /var/lib/pen-clef/clef.ipc ]; then
        chmod 660 /var/lib/pen-clef/clef.ipc
    fi

    deb-systemd-helper unmask pen.service >/dev/null || true

    if deb-systemd-helper --quiet was-enabled pen.service; then
        deb-systemd-helper enable pen.service >/dev/null || true
    else
        deb-systemd-helper update-state pen.service >/dev/null || true
    fi
    if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true
        # upgrade
        if [ ! -z "$2" ]; then
            deb-systemd-invoke start pen.service >/dev/null || true
        fi
    fi
fi
